version: "3"
services:
  api:
    container_name: express-ts-debug
    image: express-ts-debug-img
    build:
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    volumes:
      - ./src:/app/src
    ports:
      - "3000:3000"
      - "9229:9229"